- platform: template
  switches:
    projector:
      value_template: "{{ is_state_attr('remote.harmony_kjeller', 'current_activity', 'Watch Apple TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_kjeller
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_kjeller

- platform: template
  switches:
    julelys:
      value_template: "{{ is_state('switch.julestjerne_stue', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: 
            - switch.julekuler
            - switch.julestjerne_hoyre
            - switch.julestjerne_venstre
            - switch.julestjerne_stue
            - switch.juletre_mini
      turn_off:
        service: switch.turn_off
        data:
          entity_id: 
            - switch.julekuler
            - switch.julestjerne_hoyre
            - switch.julestjerne_venstre
            - switch.julestjerne_stue
            - switch.juletre_mini

- platform: template
  switches:
    octoprint_connector:
      friendly_name: "Connect Octoprint"
      value_template: "{{ not is_state('sensor.octoprint_current_state', 'unknown') }}"
      turn_on:
        service: shell_command.octoprint_connect
      turn_off:
        service: shell_command.octoprint_disconnect