- platform: template
  switches:
    projector:
      value_template: "{{ is_state_attr('remote.harmony_kjeller', 'current_activity', 'Watch Apple TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_kjeller
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_kjeller