homeassistant:
  name: Hjemme
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 110
  unit_system: metric
  time_zone: Europe/Oslo
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.64.0/23
  packages: !include_dir_named components

config:
updater:
system_health:
sun:

discovery:
  ignore:
    - sabnzbd

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml