homeassistant:
  name: Hjemme
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 110
  unit_system: metric
  time_zone: Europe/Oslo
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.64.0/23
      trusted_users:
        192.168.64.0/23: f76b971fda72441d847314773ffbdcd6
    - type: homeassistant
  customize: !include_dir_merge_named customize
  packages: !include_dir_named components

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # server_host: 127.0.0.1
  # Update this line to be your domain
  base_url: !secret domain
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: !secret proxy

config:
updater:
system_health:
sun:
mobile_app:

discovery:
  ignore:
    - sabnzbd

lovelace:
  mode: yaml

logger:
  logs:
    custom_components.iphonedetect: debug

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches