title: Hjemme

resources:
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
    type: js

custom_header:
  compact_mode: true
  background: transparent url("https://goo.gl/M3Dsf2")
  disable_sidebar: true
  options_hide: true

views:
  - !include lovelace/main.yaml
  - !include lovelace/kitchen.yaml
  - !include lovelace/livingroom.yaml
  - !include lovelace/basement.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/bedroom_madelen.yaml
  - !include lovelace/bedroom_vilde.yaml
  - !include lovelace/office.yaml
