title: Hjemme

resources:
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
  - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
    type: js
  - url: /hacsfiles/kiosk-mode/kiosk-mode.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module

#custom_header:
#  compact_mode: true
#  tab_icons_and_text: true
#  background: transparent url("https://goo.gl/M3Dsf2")
#  background: 'rgba(0, 0, 0, 0.0)'
#  disable_sidebar: true
#  options_hide: true



views:
  - !include lovelace/main.yaml
  - !include lovelace/kitchen.yaml
  - !include lovelace/livingroom.yaml
  - !include lovelace/basement.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/bedroom_madelen.yaml
  - !include lovelace/bedroom_vilde.yaml
  - !include lovelace/office.yaml
  #- !include lovelace/corona.yaml
  #- !include lovelace/corona2.yaml