title: Hjemme

resources:
  - url: /local/slider-entity-row.js?v=46be70e
    type: module
  - url: /local/toggle-lock-entity-row.js?v=a57ac15
    type: module
  - url: /local/attribute-entity-row.js?v=1.1.0
    type: module
  - url: /local/multiple-entity-row.js?v=1.3.0
    type: module
  - url: /local/github-entity-row.js?v=1.0.0
    type: module
  - url: /local/battery-entity.js?v=0.1.0
    type: module
  - url: /local/weather-card.js?v=bc4a508
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /local/simple-thermostat.js?v=0.21.0
    type: module
  - url: /local/xiaomi-vacuum-card.js?v=2.3.0
    type: module
  - url: /local/mini-media-player.js?v=1.0.3
    type: module
  - url: /local/mini-graph-card.js?v=0.3.3
    type: module
  - url: /local/compact-custom-header.js?v=0.0.1
    type: module

cch:
  background: transparent url("https://goo.gl/M3Dsf2")
  options: hide
  disable_sidebar: true
  swipe: true

views:
  - !include lovelace/main.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/bedroom_madelen.yaml
  - !include lovelace/bedroom_vilde.yaml
  - !include lovelace/office.yaml
