title: Hjemme

resources:
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module

cch:
  background: transparent url("https://goo.gl/M3Dsf2")
  options: hide
  disable_sidebar: true
  swipe: true

views:
  - !include lovelace/main.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/bedroom_madelen.yaml
  - !include lovelace/bedroom_vilde.yaml
  - !include lovelace/office.yaml
