- platform: template
  sensors:
    template_door_alarm:
      friendly_name: 'Verisure Alarm'
      icon_template: >
        {% if is_state("alarm_control_panel.svaneveien_alarm", "disarmed") %} mdi:shield-off
        {% elif is_state("alarm_control_panel.svaneveien_alarm", "armed_home") %} mdi:shield-home-outline
        {% else %} mdi:shield-home
        {% endif %}
      value_template: >
        {% if is_state("alarm_control_panel.svaneveien_alarm", "disarmed") %}Av
        {% elif is_state("alarm_control_panel.svaneveien_alarm", "armed_home") %}Skallmodus
        {% else %}På
        {% endif %}
    template_magnet_door_main:
      friendly_name: 'Ytterdør'
      icon_template: >
        {% if is_state("input_boolean.ytterdor_lock", "on") and is_state("binary_sensor.hoveddor", "off") %} mdi:door-closed-lock
        {% elif is_state("input_boolean.ytterdor_lock", "off") and is_state("binary_sensor.hoveddor", "off") %} mdi:door-closed
        {% else %} mdi:door-open
        {% endif %}
      value_template: >
        {% if is_state("input_boolean.ytterdor_lock", "on") and is_state("binary_sensor.hoveddor", "off") %}Låst
        {% elif is_state("input_boolean.ytterdor_lock", "off") and is_state("binary_sensor.hoveddor", "off") %}Lukket
        {% else %}Åpen!
        {% endif %}
    template_magnet_door_basement_main:
      friendly_name: 'Kjellerdør'
      icon_template: >
        {% if is_state("input_boolean.kjellerdor_lock", "on") and is_state("binary_sensor.hoveddor", "off") %} mdi:door-closed-lock
        {% else %} mdi:door-open
        {% endif %}
      value_template: >
        {% if is_state("input_boolean.kjellerdor_lock", "on") and is_state("binary_sensor.hoveddor", "off") %}Låst
        {% else %}Åpen!
        {% endif %}
    template_magnet_door_basement:
      friendly_name: 'Kjellerboddør'
      icon_template: >
        {% if is_state("binary_sensor.kjellerdor", "off") %} mdi:door-closed
        {% else %} mdi:door-open
        {% endif %}
      value_template: >
        {% if is_state("binary_sensor.kjellerdor", "off") %}Lukket
        {% else %}Åpen!
        {% endif %}
    template_magnet_door_livingroom:
      friendly_name: 'Stuedør'
      icon_template: >
        {% if is_state("binary_sensor.stuedor", "off") %} mdi:door-closed
        {% else %} mdi:door-open
        {% endif %}
      value_template: >
        {% if is_state("binary_sensor.stuedor", "off") %}Lukket
        {% else %}Åpen!
        {% endif %}
    template_magnet_window_kitchen_left:
      friendly_name: 'Kjøkkenvindu venstre'
      icon_template: >
        {% if is_state("binary_sensor.kjokkenvindu_venstre", "off") %} mdi:window-closed-variant
        {% else %} mdi:window-open-variant
        {% endif %}
      value_template: >
        {% if is_state("binary_sensor.kjokkenvindu_venstre", "off") %}Lukket
        {% else %}Åpen!
        {% endif %}
    template_magnet_window_kitchen_right:
      friendly_name: 'Kjøkkenvindu høyre'
      icon_template: >
        {% if is_state("binary_sensor.kjokkenvindu_hoyre", "off") %} mdi:window-closed-variant
        {% else %} mdi:window-open-variant
        {% endif %}
      value_template: >
        {% if is_state("binary_sensor.kjokkenvindu_hoyre", "off") %}Lukket
        {% else %}Åpen!
        {% endif %}
    template_magnet_window_livingroom:
      friendly_name: 'Stuevindu'
      icon_template: >
        {% if is_state("binary_sensor.stuevindu", "off") %} mdi:window-closed-variant
        {% else %} mdi:window-open-variant
        {% endif %}
      value_template: >
        {% if is_state("binary_sensor.stuevindu", "off") %}Lukket
        {% else %}Åpen!
        {% endif %}